### ISSUE TITLE
Panic inserting invalid type to DECIMAL

### ISSUE THREAD

**Issue by xhit** [SAP/go-hdb#76]
When I try to insert a invalid type to a `DECIMAL` column, I expect and error `converting $x type`, but I get a `panic: invalid decimal value` when `DECIMAL` column is not the first in the `INSERT` query.

Driver version: v0.104.0
SAP Hana Version: 2.00.045.00 Build 1575639312-1530 (Docker Container)
Client OS: Ubuntu 20.04 x64

Repro code:

```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/SAP/go-hdb/driver"
)

func main() {
	// create dsn
	dsn := fmt.Sprintf("hdb://%s:%s@%s:%d", "SYSTEM", "password", "localhost", 39017)

	// open db
	db, err := sql.Open("hdb", dsn)
	if err != nil {
		log.Print(err)
		return
	}

	err = db.Ping()
	if err != nil {
		log.Print(err)
		return
	}

	defer db.Close()

	table := "issue76"

	// drop table if exists
	db.Exec("drop table " + table)

	// drop table at end for cleaning
	defer db.Exec("drop table " + table)

	// create the table
	_, err = db.Exec("create table " + table + " (a DECIMAL(18,2),b VARCHAR(1))")
	if err != nil {
		log.Print(err)
		return
	}

	var t float64
	var s string

	q1 := "insert into " + table + "(a,b) values (?,?)"
	stmt1, _ := db.Prepare(q1)

	// this log and error, but not panic
	_, err = stmt1.Exec(t, s)
	if err != nil {
		log.Print(err)
	}
	stmt1.Close()

	fmt.Println("==================================================================================================")

	q2 := "insert into " + table + "(b,a) values (?,?)"
	stmt2, _ := db.Prepare(q2)

	// this panic because DECIMAL is not the first to insert
	_, err = stmt2.Exec(s, t)
	if err != nil {
		log.Print(err)
	}

	stmt2.Close()
}
```

Panic message:
```
panic: invalid decimal value

goroutine 25 [running]:
github.com/SAP/go-hdb/internal/protocol.encodeFixed(0xc00008c050, 0x652d00, 0x8327e0, 0x8, 0x12, 0x2, 0x0, 0x0)
        /home/santiago/goprojects/pkg/mod/github.com/!s!a!p/go-hdb@v0.104.0/internal/protocol/fieldtype.go:521 +0xff
github.com/SAP/go-hdb/internal/protocol._fixed8Type.encodePrm(...)
        /home/santiago/goprojects/pkg/mod/github.com/!s!a!p/go-hdb@v0.104.0/internal/protocol/fieldtype.go:507
github.com/SAP/go-hdb/internal/protocol.(*ParameterField).encodePrm(0xc00011d170, 0xc00008c050, 0x652d00, 0x8327e0, 0x0, 0x0)
        /home/santiago/goprojects/pkg/mod/github.com/!s!a!p/go-hdb@v0.104.0/internal/protocol/parameter.go:168 +0x8c
github.com/SAP/go-hdb/internal/protocol.(*inputParameters).encode(0xc000158240, 0xc00008c050, 0xc0000160b0, 0x0)
        /home/santiago/goprojects/pkg/mod/github.com/!s!a!p/go-hdb@v0.104.0/internal/protocol/parameter.go:287 +0xc5
github.com/SAP/go-hdb/internal/protocol.(*protocolWriter).write(0xc00008c0a0, 0x214e3e1295f77, 0xc00005010d, 0xc000069e40, 0x2, 0x2, 0x40f63b, 0xc00012e120)
        /home/santiago/goprojects/pkg/mod/github.com/!s!a!p/go-hdb@v0.104.0/internal/protocol/protocol.go:802 +0x49f
github.com/SAP/go-hdb/internal/protocol.(*Session).exec(0xc00008e090, 0xc000080140, 0xc00014a700, 0x2, 0x2, 0x6f0100, 0xc00012e120, 0x5fc201, 0xc00008c0a0, 0x0)
        /home/santiago/goprojects/pkg/mod/github.com/!s!a!p/go-hdb@v0.104.0/internal/protocol/session.go:341 +0x196
github.com/SAP/go-hdb/internal/protocol.(*Session).Exec(0xc00008e090, 0xc000080140, 0xc00014a700, 0x2, 0x2, 0xc00008e001, 0xc00014c138, 0x12, 0xc00011d110, 0xc000118a38)
        /home/santiago/goprojects/pkg/mod/github.com/!s!a!p/go-hdb@v0.104.0/internal/protocol/session.go:295 +0xb4
github.com/SAP/go-hdb/driver.(*stmt).exec.func1(0xc00008c1e0, 0xc0001384e0, 0xc00014a700, 0x2, 0x2, 0xc000118a80, 0xc000118a90, 0xc00010e3c0)
        /home/santiago/goprojects/pkg/mod/github.com/!s!a!p/go-hdb@v0.104.0/driver/connection.go:878 +0x6d
created by github.com/SAP/go-hdb/driver.(*stmt).exec
        /home/santiago/goprojects/pkg/mod/github.com/!s!a!p/go-hdb@v0.104.0/driver/connection.go:877 +0x445
```

**Comment by stfnmllr** [comment]
@xhit Are you sure that you are using an unmodified go-hdb version?

Testing your example on v0.104.0 gives me for the first insert
`sql: converting argument $1 type: unsupported fixed8Type conversion: float64 0`
and the second
`sql: converting argument $1 type: unsupported fixed8Type conversion: string`

which does mean, that currently whether floats nor string types are supported for decimal variables.

**Comment by stfnmllr** [comment]
Thanks for the example - https://github.com/SAP/go-hdb/releases/tag/v0.104.1 should fix the issue.
